add default values option for Dialog
prompt-toolkit/python-prompt-toolkit pull request #1563
Opened 2022-02-07 12:33 UTC by motty-mio2

Hello, I'm happy to post here.

## Why
Default Value settings are important for some people (includes me).

## What
I add an option to set default value for Dialogs(Checkbox list dialog and Radio list dialog).

- It can check whether the value is valid or invalid.
  - later checkbox example, "banana" is not a valid option, so it is removed. "eggs" and "croissants" are selected.

## Usage
### Checkbox list dialog
```
results_array = checkboxlist_dialog(
    title="CheckboxList dialog",
    text="What would you like in your breakfast ?",
    values=[
        ("eggs", "Eggs"),
        ("bacon", "Bacon"),
        ("croissants", "20 Croissants"),
        ("daily", "The breakfast of the day")
    ],
    default_values=["banana", "eggs", "croissants"]
).run()
All values in default_values will be used for default value.
```
### Radio list dialog
```
result = radiolist_dialog(
    values=[
        ("red", "Red"),
        ("green", "Green"),
        ("blue", "Blue"),
        ("orange", "Orange"),
    ],
    default_values=["blue"],
    title="Radiolist dialog example",
    text="Please select a color:",
).run()
```
First index (default_values[0], in this case "blue") item will be used for default value.

## How It Works
### checkbox dialogs
I set default_values as `["banana", "eggs", "croissants"]`
![checkbox](https://user-images.githubusercontent.com/11750226/152786572-8ffb7f99-6386-46ab-89ef-9a743886824c.gif)
  
### radio dialogs
I set default_values as `["blue"]`
"blue" is selected.  
![radio](https://user-images.githubusercontent.com/11750226/152786108-dc3e78f4-8047-4d58-9e73-af8a66c03be4.gif)

## Related
- issue
    - #1544 
- PR
    - #651

Thank you.

2022-02-09 15:28 UTC, jonathanslenders requested changes
Looks good overall. A few small comments.

2022-02-09 15:28 UTC, jonathanslenders commented on prompt_toolkit/shortcuts/dialogs.py
> +    default_values: List[_T] = [],
mutable values should not be used as keyword arguments. State could leak from one call to the next.

Better is to do:
```python
default_values: Optional[List[_T]] = None,
```

and in the body of the function:
```python
if default_values is None:
    default_values = []
```

2022-02-09 15:28 UTC, jonathanslenders commented on prompt_toolkit/shortcuts/dialogs.py
> +    default_values: List[_T] = [],
Same comment here about mutable defaults.

2022-02-09 15:28 UTC, jonathanslenders commented on prompt_toolkit/widgets/base.py
> +        self, values: Sequence[Tuple[_T, AnyFormattedText]], default_values: List[_T]
Same comment about mutable defaults here.

2022-02-09 15:28 UTC, jonathanslenders commented on prompt_toolkit/widgets/base.py
> +            if (default_value in candidate)
no parentheses are required around this expression.

2022-02-11 08:45 UTC, jonathanslenders commented
@motty-mio2: I did some changes to this pull request, and merged it from here: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1569
Thanks again for the contribution!

2022-02-11 08:45 UTC, closed without merging

2022-02-11 08:54 UTC, motty-mio2 commented
Oh Thank you so much.